# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
