# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170709_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lng',
        ),
    ]
