# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20170712_1932'),
        ('places', '0004_auto_20170710_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetailInTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('comment', models.CharField(blank=True, max_length=140)),
                ('rating', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='associated_trips',
            field=models.ManyToManyField(blank=True, through='places.PlaceDetailInTrip', to='trips.Trip'),
        ),
    ]
