# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170719_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map_image',
            field=models.ImageField(default='places/google_map_images/default.png', upload_to='places/google_map_images/'),
        ),
        migrations.AlterField(
            model_name='placedetailinatrip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_in_a_trip', to='places.Place'),
        ),
    ]
