# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placedetailinatrip_time_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePlaceSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.PositiveIntegerField(default=0)),
                ('place1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place1', to='places.Place')),
                ('place2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place2', to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='similarPlaces',
            field=models.ManyToManyField(blank=True, related_name='similar_place_list', through='places.PlacePlaceSimilarity', to='places.Place'),
        ),
    ]
