# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('trips', '0002_auto_20170709_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_visit', models.IntegerField(default=0)),
                ('order_in_trip', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='place_visited',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place_visited',
            name='trip',
        ),
        migrations.AlterField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(through='trips.PlaceVisited', to='places.Place'),
        ),
        migrations.DeleteModel(
            name='Place_visited',
        ),
        migrations.AddField(
            model_name='placevisited',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
