# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20170709_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevisited',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
