# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_placevisited_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='thumbnail_origin',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails/'),
        ),
    ]
