# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_thumbnail_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placevisited',
            old_name='days_to_visit',
            new_name='days_to_stay',
        ),
        migrations.AddField(
            model_name='placevisited',
            name='travel_mode_to_next',
            field=models.CharField(choices=[('Driving', 'Driving'), ('Transit', 'Transit'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Flight', 'Flight'), ('End', 'End')], default='End', max_length=9),
        ),
    ]
