# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20170709_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placevisited',
            old_name='travel_mode_to_next',
            new_name='travel_mode_to_here',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
