# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20170713_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_place_list', to='trips.Trip'),
        ),
    ]
