# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_auto_20170713_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='updated',
            new_name='updated_time',
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
