# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20170713_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_distance_meters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
