# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0015_auto_20170713_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='people_liked_this',
            field=models.ManyToManyField(blank=True, related_name='trips_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
