# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_auto_20170713_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='op_comment',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
