# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_trip_op_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='trip',
            name='looking_for_partner',
            field=models.BooleanField(default=False),
        ),
    ]
