# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_placevisited_encoded_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='group_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
