# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_trip_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevisited',
            name='travel_mode_to_here',
            field=models.CharField(choices=[('Driving', 'DRIVING'), ('Walking', 'WALKING'), ('Cycling', 'BICYCLING'), ('START', 'START')], default='START', max_length=9),
        ),
    ]
