# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_auto_20170718_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevisited',
            name='note_in_here',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='note_to_here',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
