# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_auto_20170721_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placevisited',
            old_name='displayed_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='placevisited',
            name='days_to_stay',
        ),
        migrations.RemoveField(
            model_name='placevisited',
            name='encoded_polyline',
        ),
        migrations.RemoveField(
            model_name='placevisited',
            name='note_in_here',
        ),
        migrations.RemoveField(
            model_name='placevisited',
            name='note_to_here',
        ),
        migrations.AddField(
            model_name='placevisited',
            name='note',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='time_arrival',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='time_departure',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='time_zone_dstOffset',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='time_zone_rawOffset',
            field=models.IntegerField(default=-28800),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
