# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_auto_20170725_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevisited',
            name='time_arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='time_departure',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
