# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_auto_20170725_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placevisited',
            old_name='custome_name',
            new_name='custom_name',
        ),
    ]
