# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_auto_20170727_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='placevisited',
            name='prev_place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_place', to='trips.PlaceVisited'),
        ),
        migrations.AlterField(
            model_name='placevisited',
            name='travel_mode_to_here',
            field=models.CharField(choices=[('Driving', 'DRIVING'), ('Transit', 'TRANSIT'), ('Walking', 'WALKING'), ('Cycling', 'BICYCLING'), ('START', 'START')], default='START', max_length=10),
        ),
        migrations.AddField(
            model_name='placevisited',
            name='unavailable_modes',
            field=models.ManyToManyField(blank=True, related_name='not_available_in', to='trips.TravelMode'),
        ),
    ]
