# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_auto_20170728_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placevisited',
            name='prev_place',
        ),
    ]
