# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0033_placevisited_prev_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevisited',
            name='encoded_polyline',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
