# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0035_remove_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placevisited',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='placevisited',
            name='pin_mode',
            field=models.CharField(choices=[('neither', 'neither'), ('departure', 'departure'), ('duration', 'duration')], default='neither', max_length=20),
        ),
    ]
