# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0036_auto_20170731_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevisited',
            name='show_suggested_name',
            field=models.BooleanField(default=False),
        ),
    ]
