# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0037_placevisited_show_suggested_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevisited',
            name='is_tag_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
